### ISSUE TITLE
添加 Kafka 线程池监控及动态变更

### ISSUE THREAD

**Issue by mabaiwan** [mabaiwan/hippo4j#229]

**Comment by lishiyu** [comment]
可以详细说一下需求吗

**Comment by longtai-cn** [comment]
以 SpringCloud Stream RocketMQ 举例：

1. 在 hippo4j-server 其它线程池页面，可以根据线程池类型搜索到指定租户、指定项目下的线程池；

![image](https://user-images.githubusercontent.com/77398366/169042971-1440a679-c958-4dc3-8663-7829f86b2255.png)

2. 在该页面，可以对线程池数据进行动态修改；
3. 开发者仅需填充 cn.hippo4j.adapter.kafka.KafkaThreadPoolAdapter 即可

**Comment by mabaiwan** [comment]
spring kafka 无法支持线程池动态变更，在消费时使用动态线程池即可。
