### ISSUE TITLE
修改tomcat线程池抛ClassCastException

### ISSUE THREAD

**Issue by hanspipe** [mabaiwan/hippo4j#259]
## Bug Report

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/mabaiwan/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/pages/9cc27d/)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？Hippo-4J Server 还是 Hippo-4J Core?
 Hippo-4J Core

### 你使用了哪个版本？
1.2.1/1.3.0

### 预期行为
配置中心修改tomcat线程池相关参数时能够正确修改

### 实际行为
![image](https://user-images.githubusercontent.com/30045908/172365446-21a9e944-dfbd-42f7-bceb-a051562899b2.png)

### 原因分析（如果可以）
TomcatWebThreadPoolHandler里import的是jdk的ThreadPoolExecutor，会导致类型转换的时候ClassCastException

### 问题重现步骤
修改tomcat线程池参数

**Comment by mabaiwan** [comment]
springboot 用的什么版本，有没有对 tomcat 线程池做定制化操作呢

**Comment by hanspipe** [comment]
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/30045908/172378341-bcad3107-8c3d-438d-9457-626c30d824f1.png">
tomcat版本：9.0.55
tomcat版本问题，tomcat的ThreadPoolExecutor非继承自jdk的ThreadPoolExecutor导致无法类型转换，是否考虑对不同tomcat版本的ThreadPoolExecutor实现方式做兼容方案。

**Comment by mabaiwan** [comment]
这个问题我单独起个适配的 issue 吧，如果你有兴趣可以看下 https://github.com/mabaiwan/hippo4j/issues/260

**Comment by mabaiwan** [comment]
@hanspipe 高版本 tomcat 线程池适配已完成 https://github.com/mabaiwan/hippo4j/issues/260
