### ISSUE TITLE
是否有必要支持将Hippo4J 客户端和服务集成在一起使用

### ISSUE THREAD

**Issue by baymax55** [mabaiwan/hippo4j#261]
## Feature Request

请在提交问题之前回答这些问题，谢谢。

### 您的功能请求是否与问题有关？
是
### 描述你想要的功能
1.将客户端和服务集成在一起使用,即在一个服务内支持管理和配置线程池
2.是否有必要将server提供一个starter来使用

**Comment by mabaiwan** [comment]
不可以，存在单点和内存中数据无法解决问题
