### ISSUE TITLE
Apollo配置修改延迟了一个版本

### ISSUE THREAD

**Issue by sheep1324** [mabaiwan/hippo4j#267]
## Bug Report
 类似 issue#164情况 https://github.com/mabaiwan/hippo4j/issues/164

###  版本
Hippo-4J Core  1.3.0

### 预期行为
  Apollo发布A线程池的配置为Ver1，应用监听变更并把A线程池的配置改为Ver1

### 实际行为
   Apollo发布A线程池的配置为Ver1，应用监听到变更，但没有把A线程池的配置改为Ver1。Apollo再次发布Ver2配置，此时应用把A线程池的配置改成了Ver1

### 原因分析（如果可以）
   `ApolloRefresherHandler`中配置的`ConfigChangeListener`监听器，变更事件触发后`ConfigService.getConfigFile`第二次触发开始是从内存获取配置信息，此时内存未更新，所以拿到的是变更前的配置。

### 问题重现步骤
   1. 应用启动后，Apollo修改一次配置为V1，此时更新是成功的；
   2. 再次修改配置为V2，没有触发更新；
   3. 再次修改配置为V3，触发更新，但更新为V2

**Comment by mabaiwan** [comment]
感谢反馈。

**Comment by mabaiwan** [comment]
根据我的判断，apollo 触发线程池配置变更后，监听事件中会获取 ConfigService.getConfigFile 最新配置，但是只有第一次是最新的，第二次不更新，第三次触发第二次，以此类推。

**Comment by sheep1324** [comment]
> 根据我的判断，apollo 触发线程池配置变更后，监听事件中会获取 ConfigService.getConfigFile 最新配置，但是只有第一次是最新的，第二次不更新，第三次触发第二次，以此类推。

嗯，第二次开始获取到的是变更前配置。可以考虑改用`ConfigFileChangeListener`事件的`getNewValue()`获取最新配置

**Comment by mabaiwan** [comment]
在没有找到真正配置延迟原因前，这是个好办法
