### ISSUE TITLE
hippo4j-core 配置线程池监控，Grafana DashBoard 未展示数据

### ISSUE THREAD

**Issue by sdauhan** [mabaiwan/hippo4j#268]
hippo4j-core-nacos-spring-boot-starter-example 启动此工程，配置动态线程池监控，grafana未展示数据。

使用的是Hippo-4J Core项目，版本是1.3.1-SNAPSHOT
nacos版本2.1.0
prometheus版本2.36.2
grafana版本9.0.1

按照这个文档地址进行操作的
https://hippo4j.cn/docs/getting-started/hippo4j-core-start

### 预期行为
grafana可以看到线程池监控数据

### 实际行为
grafana未能看到线程池监控数据

### 问题重现步骤

1、启动nacos，prometheus，grafana
2、prometheus修改为mysql，重新启动
3、启动hippo4j-core-nacos-spring-boot-starter-example工程，在prometheus中的status tab下的target列表中看到up状态
4、按照文档在grafana中配置数据源和dashboard，json选用的是
 https://pan.baidu.com/s/1ccbTBwW6HzOHmqQXmXzB_g 这个里面的

这是所有的步骤。

辛苦帮忙看下，谢谢！

**Comment by Oliverwqcwrw** [comment]
我也遇到了同样的问题，最后发现是prometheus拿到数据的时间和当前时间差八个小时，而grafana查询数据默认查询最近5s，我改成查询最近12小时就有数据了
ps：我是自己创建的panel，导入的确实不好使

**Comment by Oliverwqcwrw** [comment]
看了一下导入的json，问题在于uid

> "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "dO7ivQqnk"
          },
          "exemplar": true,
          "expr": "dynamic_thread_pool_current_load{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\",}",
          "interval": "",
          "legendFormat": "{{instance}}",
          "refId": "A"
        }
      ],

我把uid改成和我自己创建的panel相同的值，所有数据都可以展示了，我理解这个uid应该是对应创建的datasource的唯一值，我们不能用原始的uid，因为那是作者的datasource唯一值，我们需要替换为我们自己datasource的唯一值。 @sdauhan 你可以先自己创建一个panel，看一下对应的datasource的uid然后替换一下就可以了

ps：只需要修改panel对应的uid，全局的uid不需要改

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/31796988/176335574-6757f38b-f556-45eb-86b7-dfa0ec13f884.png">
