### ISSUE TITLE
Dubbo 监控统计数据有误

### ISSUE THREAD

**Issue by Oliverwqcwrw** [mabaiwan/hippo4j#274]
## Question Report

在开始报告问题之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/mabaiwan/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/pages/9cc27d/)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？Hippo-4J Server 还是 Hippo-4J Core?

Hippo-4J Core

### 你使用了哪个版本？

1.3.0

### 预期行为

可以监控dubbo线程池的变化并且动态修改，帮忙提供一下完整的yaml配置，如果需要配置Bean，也帮忙提供一下，非常感谢

### 实际行为

无法配置并监控dubbo线程池

### 原因分析（如果可以）

不知道如何配置，看文档只有一小部分

**Comment by Oliverwqcwrw** [comment]
我按官网的试了一下：
我的配置：

> 
adapter-executors:
        # threadPoolKey 代表线程池标识
        - threadPoolKey: 'dubbo-provider'
          # mark 为三方线程池框架类型，参见文初已支持框架集合
          mark: 'Dubbo'
          corePoolSize: 50
          maximumPoolSize: 50

prometheus拿到的数据是40和60:

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/31796988/177707715-84b04b1d-4d3b-48a3-ab91-7c1b42e52760.png">

**Comment by Oliverwqcwrw** [comment]
通过调试，dubbo的线程数确实变了，应该是metric一直没有拿到dubbo的线程池的真实数据，一直拿的是默认的数据，想咨询一下dubbo的线程池监控怎么配置Bean呢？

**Comment by mabaiwan** [comment]
这种测试方式有问题。adapter-executors 下面的配置属于 dubbo 框架原生线程池，而不是你通过代码自定义的线程池。

**Comment by Oliverwqcwrw** [comment]
如果想要监控dubbo的线程池，需要怎么配置呢，我一开始只配置yaml没有配置Bean是不会有监控数据的，但是这种方式配置Bean应该也不太对，应该是针对自定义线程池才会这样配置，实在是没有其他办法了，然后我这样配置了一下Bean，修改了一下源码，然后可以做到监控dubbo线程池数据，如果目前对于这种引入hippo4j-core支持监控dubbo的话，辛苦发一下配置，非常感谢 :)

**Comment by mabaiwan** [comment]
目前并不支持三方线程池监控功能。1.3.3 版本计划会把监控单独抽出去一个模块，以微内核的方式运行。

**Comment by Oliverwqcwrw** [comment]
好吧，因为我们要做三方线程池监控并动态修改线程数，我会先通过自己修改源码的方式实现，期待支持三方线程池监控功能 :)

**Comment by mabaiwan** [comment]
@Oliverwqcwrw 如果公司使用，https://github.com/mabaiwan/hippo4j/issues/13 麻烦登记下，谢谢。

**Comment by Oliverwqcwrw** [comment]
嗯那，还在调研阶段，如果采用了您的方案，我会登记的 您的设计确实很棒 :)
