### ISSUE TITLE
线程池未被GC

### ISSUE THREAD

**Issue by nulinuli-nuli** [mabaiwan/hippo4j#278]
## Bug Report

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/mabaiwan/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/pages/9cc27d/)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？Hippo-4J Server 还是 Hippo-4J Core?
Hippo-4J Server
### 你使用了哪个版本？
1.3.0
### 预期行为
拉取服务端参数之前创建的线程池被GC
### 实际行为
未被GC
### 原因分析（如果可以）
未知
### 问题重现步骤
按照文档初始化，随后利用诊断工具查看内存中的对象

**Comment by mabaiwan** [comment]
正常来说，旧的线程池已经不存在引用了，下次 GC 时会被回收。你有测试 GC 后是否存在么？

**Comment by mabaiwan** [comment]
无响应，issue 关闭，如有问题可再次开启该 issue
