### ISSUE TITLE
hippo4j server 模式下支持 promethus

### ISSUE THREAD

**Issue by mushuijingjing** [mabaiwan/hippo4j#287]
### 描述你想要的功能

server模式下数据存储在mysql，在数据量较大的情况下，性能是个瓶颈，可否存储到promethus

**Comment by mabaiwan** [comment]
你值得所有数据，还是线程池监控数据

**Comment by mushuijingjing** [comment]
> 

线程池监控数据

**Comment by mabaiwan** [comment]
留有扩展点，只不过还没有实现。你提到的 mysql 数据量较大的问题，参考这个 issue https://github.com/mabaiwan/hippo4j/issues/62
